package org.fbi.hmfsjm.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.hmfsjm.repository.model.HmfsJmDraw;
import org.fbi.hmfsjm.repository.model.HmfsJmDrawExample;

public interface HmfsJmDrawMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int countByExample(HmfsJmDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int deleteByExample(HmfsJmDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int insert(HmfsJmDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int insertSelective(HmfsJmDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    List<HmfsJmDraw> selectByExample(HmfsJmDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    HmfsJmDraw selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByExampleSelective(@Param("record") HmfsJmDraw record, @Param("example") HmfsJmDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByExample(@Param("record") HmfsJmDraw record, @Param("example") HmfsJmDrawExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByPrimaryKeySelective(HmfsJmDraw record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_DRAW
     *
     * @mbggenerated Wed Oct 15 16:03:32 CST 2014
     */
    int updateByPrimaryKey(HmfsJmDraw record);
}