package org.fbi.hmfsjm.repository.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.fbi.hmfsjm.repository.model.HmfsJmIrt;
import org.fbi.hmfsjm.repository.model.HmfsJmIrtExample;

public interface HmfsJmIrtMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int countByExample(HmfsJmIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int deleteByExample(HmfsJmIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int insert(HmfsJmIrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int insertSelective(HmfsJmIrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    List<HmfsJmIrt> selectByExample(HmfsJmIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    HmfsJmIrt selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int updateByExampleSelective(@Param("record") HmfsJmIrt record, @Param("example") HmfsJmIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int updateByExample(@Param("record") HmfsJmIrt record, @Param("example") HmfsJmIrtExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int updateByPrimaryKeySelective(HmfsJmIrt record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_IRT
     *
     * @mbggenerated Wed Oct 15 16:38:01 CST 2014
     */
    int updateByPrimaryKey(HmfsJmIrt record);
}