package org.fbi.hmfsjm.repository.dao;

import org.fbi.hmfsjm.repository.model.HmfsJmActDel;
import org.fbi.hmfsjm.repository.model.HmfsJmActDelExample;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface HmfsJmActDelMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int countByExample(HmfsJmActDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int deleteByExample(HmfsJmActDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int deleteByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int insert(HmfsJmActDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int insertSelective(HmfsJmActDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    List<HmfsJmActDel> selectByExample(HmfsJmActDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    HmfsJmActDel selectByPrimaryKey(String pkid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int updateByExampleSelective(@Param("record") HmfsJmActDel record, @Param("example") HmfsJmActDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int updateByExample(@Param("record") HmfsJmActDel record, @Param("example") HmfsJmActDelExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int updateByPrimaryKeySelective(HmfsJmActDel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table FIS.HMFS_JM_ACT_DEL
     *
     * @mbggenerated Tue Nov 19 16:19:20 CST 2013
     */
    int updateByPrimaryKey(HmfsJmActDel record);
}